// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NegoSudAPI.Data;

#nullable disable

namespace NegoSudAPI.Migrations
{
    [DbContext(typeof(NegosudDbContext))]
    partial class NegosudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NegoSudAPI.Models.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseComplet")
                        .HasColumnType("longtext");

                    b.Property<string>("AdressePrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("CodePostal")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Pays")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Rue")
                        .HasColumnType("longtext");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("Ville")
                        .HasColumnType("longtext");

                    b.Property<string>("typeAdresse")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("adresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdresseComplet = "13 rue des champettle",
                            AdressePrincipal = "rue des champelle",
                            CodePostal = "15312",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(8930),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(8960),
                            Pays = "France",
                            Region = "Normandie",
                            UtilisateurId = 1,
                            Ville = "Rouen"
                        },
                        new
                        {
                            Id = 2,
                            AdresseComplet = "13 rue des champettle",
                            AdressePrincipal = "rue des champelle",
                            CodePostal = "15312",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9012),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9017),
                            Pays = "France",
                            Region = "Normandie",
                            Ville = "Rouen"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Catalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("catalogues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://www.vinatis.com/62341-thickbox_default/chateauneuf-du-pape-grand-vin-2018-chateau-de-nalys-e-guigal.png",
                            ProduitId = 1,
                            Reference = "DEN12"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://www.vinatis.com/62341-thickbox_default/chateauneuf-du-pape-grand-vin-2018-chateau-de-nalys-e-guigal.png",
                            ProduitId = 2,
                            Reference = "EDE54"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameCategorie")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameCategorie = "Vin rouge"
                        },
                        new
                        {
                            Id = 2,
                            NameCategorie = "Vin Blanc"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCommande")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Remise")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("commandes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCommande = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9883),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9895),
                            Remise = 15f,
                            Statut = "en cours",
                            UtilisateurId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCommande = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(5),
                            Remise = 15f,
                            Statut = "livré",
                            UtilisateurId = 2
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.ElemCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alerte")
                        .HasColumnType("longtext");

                    b.Property<int?>("CommandeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("QuantiteCommande")
                        .HasColumnType("int");

                    b.Property<int?>("SeuilAlerte")
                        .HasColumnType("int");

                    b.Property<float>("TotalCommande")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.ToTable("elemCommandes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alerte = "seuil est dépassé",
                            CommandeId = 1,
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(70),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(77),
                            QuantiteCommande = 5,
                            SeuilAlerte = 3,
                            TotalCommande = 64.21f
                        },
                        new
                        {
                            Id = 2,
                            Alerte = "seuil est dépassé",
                            CommandeId = 2,
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(83),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(86),
                            QuantiteCommande = 5,
                            SeuilAlerte = 3,
                            TotalCommande = 66.21f
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.ElemFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FactureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("elemFactures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(218),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(225),
                            FactureId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(230),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(233),
                            FactureId = 2
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommandeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("FactureTotal")
                        .HasColumnType("float");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.ToTable("factures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommandeId = 1,
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(137),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(144),
                            FactureTotal = 45.3f,
                            Reference = "FR656D"
                        },
                        new
                        {
                            Id = 2,
                            CommandeId = 1,
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(148),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 832, DateTimeKind.Local).AddTicks(152),
                            FactureTotal = 45.3f,
                            Reference = "FR326D"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fix")
                        .HasColumnType("longtext");

                    b.Property<string>("NomFournisseur")
                        .HasColumnType("longtext");

                    b.Property<string>("Pays")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Reputation")
                        .HasColumnType("longtext");

                    b.Property<string>("Rue")
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext");

                    b.Property<string>("Ville")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("fournisseurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "13 rue des saloumé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9408),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9418),
                            Email = "fournisseur1@negosud.com",
                            Fix = "+3324515475",
                            NomFournisseur = "Fournisseur Vin blanc",
                            Pays = "France",
                            Region = "Normandie",
                            Reputation = "Excellent",
                            Rue = "12 rue des chameaux",
                            Tel = "+33678407516",
                            Ville = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "11 rue des saloumé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9430),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9434),
                            Email = "fournisseur2@negosud.com",
                            Fix = "+3324515475",
                            NomFournisseur = "Fournisseur Vin Rouge",
                            Pays = "France",
                            Region = "Normandie",
                            Reputation = "Excellent",
                            Rue = "12 rue des chameaux",
                            Tel = "+33678407516",
                            Ville = "Marsaille"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Inventaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Appelation")
                        .HasColumnType("longtext");

                    b.Property<string>("Classement")
                        .HasColumnType("longtext");

                    b.Property<string>("Couleur")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MagasinId")
                        .HasColumnType("int");

                    b.Property<string>("Millesime")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MagasinId");

                    b.ToTable("inventaires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Appelation = "Fournisseur Vin blanc",
                            Classement = "Première rayon 1C4",
                            Couleur = "Rouge Foncé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9705),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9711),
                            MagasinId = 1,
                            Millesime = "2016",
                            Nom = "Blanc rouge Chapelle",
                            Position = "2 cave, rayon 3",
                            QuantiteStock = 66
                        },
                        new
                        {
                            Id = 2,
                            Appelation = "Fournisseur Vin blanc",
                            Classement = "Première rayon 1C4",
                            Couleur = "Rouge Foncé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9717),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9720),
                            MagasinId = 2,
                            Millesime = "2016",
                            Nom = "Blanc rouge Chapelle",
                            Position = "2 cave, rayon 3",
                            QuantiteStock = 66
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Magasin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<string>("CodePostal")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fix")
                        .HasColumnType("longtext");

                    b.Property<string>("NomMagasin")
                        .HasColumnType("longtext");

                    b.Property<string>("Pays")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProducteurId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Rue")
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProducteurId");

                    b.ToTable("magasins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "13 rue des saloumé",
                            CodePostal = "65412",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9633),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9639),
                            Email = "fournisseur1@negosud.com",
                            Fix = "+3324515475",
                            NomMagasin = "Fournisseur Vin blanc",
                            Pays = "France",
                            ProducteurId = 1,
                            Region = "Normandie",
                            Rue = "12 rue des chameaux",
                            Tel = "+33678407516"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "11 rue des saloumé",
                            CodePostal = "56515",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9648),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9651),
                            Email = "fournisseur2@negosud.com",
                            Fix = "+3324515475",
                            NomMagasin = "Fournisseur Vin Rouge",
                            Pays = "France",
                            ProducteurId = 2,
                            Region = "Normandie",
                            Rue = "12 rue des chameaux",
                            Tel = "+33678407516"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Mailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnvoyePar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("receptionneur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("mailers");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Pays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NamePays")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("pays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NamePays = "France"
                        },
                        new
                        {
                            Id = 2,
                            NamePays = "Italie"
                        },
                        new
                        {
                            Id = 3,
                            NamePays = "Portugal"
                        },
                        new
                        {
                            Id = 4,
                            NamePays = "Espagne"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Producteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fix")
                        .HasColumnType("longtext");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext");

                    b.Property<string>("NomProducteur")
                        .HasColumnType("longtext");

                    b.Property<string>("Pays")
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .HasColumnType("longtext");

                    b.Property<string>("RaisonSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Reputation")
                        .HasColumnType("longtext");

                    b.Property<string>("Rue")
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext");

                    b.Property<string>("Ville")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("producteurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "13 rue des saloumé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9493),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9500),
                            Email = "fournisseur1@negosud.com",
                            Fix = "+3324515475",
                            FournisseurId = 1,
                            NomProducteur = "Fournisseur Vin blanc",
                            Pays = "France",
                            Region = "Normandie",
                            Reputation = "Excellent",
                            Rue = "12 rue des chameaux",
                            Tel = "+33678407516",
                            Ville = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "11 rue des saloumé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9507),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9570),
                            Email = "fournisseur2@negosud.com",
                            Fix = "+3324515475",
                            FournisseurId = 2,
                            NomProducteur = "Fournisseur Vin Rouge",
                            Pays = "France",
                            Region = "Normandie",
                            Reputation = "Excellent",
                            Rue = "12 rue des chameaux",
                            Tel = "+33678407516",
                            Ville = "Marsaille"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float?>("Alcool")
                        .HasColumnType("float");

                    b.Property<string>("Aliments")
                        .HasColumnType("longtext");

                    b.Property<string>("Ancien")
                        .HasColumnType("longtext");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Conservation")
                        .HasColumnType("longtext");

                    b.Property<string>("Couleur")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("ElemCommandeId")
                        .HasColumnType("int");

                    b.Property<int?>("ElemFactureId")
                        .HasColumnType("int");

                    b.Property<string>("Expiration")
                        .HasColumnType("longtext");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePrincipal")
                        .HasColumnType("longtext");

                    b.Property<int?>("InventaireId")
                        .HasColumnType("int");

                    b.Property<string>("NomProduit")
                        .HasColumnType("longtext");

                    b.Property<float?>("Prix_carton")
                        .HasColumnType("float");

                    b.Property<float?>("Prix_unitaire")
                        .HasColumnType("float");

                    b.Property<int?>("ProducteurId")
                        .HasColumnType("int");

                    b.Property<string>("Raisins")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<float?>("Remise")
                        .HasColumnType("float");

                    b.Property<string>("Resumee")
                        .HasColumnType("longtext");

                    b.Property<string>("SKU")
                        .HasColumnType("longtext");

                    b.Property<float?>("TVA")
                        .HasColumnType("float");

                    b.Property<float>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ElemCommandeId");

                    b.HasIndex("ElemFactureId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("InventaireId");

                    b.HasIndex("ProducteurId");

                    b.ToTable("produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alcool = 15.5f,
                            Aliments = "très amer et acide",
                            Ancien = "2015",
                            CategorieId = 1,
                            Conservation = "consummable jusqu'a 2029",
                            Couleur = "Rouge Foncé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9778),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9784),
                            Description = "that shit happens when the smart wenter faster minster faster",
                            Expiration = "2029",
                            ImagePrincipal = "https://www.vinatis.com/62341-thickbox_default/chateauneuf-du-pape-grand-vin-2018-chateau-de-nalys-e-guigal.png",
                            NomProduit = "Fournisseur Vin blanc",
                            Prixcarton = 15.4f,
                            Prixunitaire = 5.3f,
                            ProducteurId = 1,
                            Raisins = "Frais récolté le jenvier 2022 à saint-loire",
                            Region = "Normandie",
                            Remise = 10.5f,
                            Resumee = "smart here this gantis",
                            SKU = "CDC5454",
                            TVA = 5.14f,
                            Volume = 4.3f
                        },
                        new
                        {
                            Id = 2,
                            Alcool = 15.5f,
                            Aliments = "très amer et acide",
                            Ancien = "2015",
                            CategorieId = 1,
                            Conservation = "consummable jusqu'a 2029",
                            Couleur = "Rouge Foncé",
                            DateCreation = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9812),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(9816),
                            Description = "that shit happens when the smart wenter faster minster faster",
                            Expiration = "2029",
                            ImagePrincipal = "https://www.vinatis.com/62341-thickbox_default/chateauneuf-du-pape-grand-vin-2018-chateau-de-nalys-e-guigal.png",
                            NomProduit = "Fournisseur Vin blanc",
                            Prixcarton = 15.4f,
                            Prixunitaire = 5.3f,
                            ProducteurId = 2,
                            Raisins = "Frais récolté le jenvier 2022 à saint-loire",
                            Region = "Normandie",
                            Remise = 10.5f,
                            Resumee = "smart here this gantis",
                            SKU = "CDC5454",
                            TVA = 5.14f,
                            Volume = 4.3f
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameRegion")
                        .HasColumnType("longtext");

                    b.Property<int?>("PaysId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaysId");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameRegion = "Normandie",
                            PaysId = 1
                        },
                        new
                        {
                            Id = 2,
                            NameRegion = "Caen",
                            PaysId = 2
                        },
                        new
                        {
                            Id = 3,
                            NameRegion = "Lour",
                            PaysId = 3
                        },
                        new
                        {
                            Id = 4,
                            NameRegion = "Paris",
                            PaysId = 4
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsBusiness")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext");

                    b.Property<string>("NomUtilisateur")
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .HasColumnType("longtext");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SIREN")
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateInscription = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(8127),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(8227),
                            Email = "ismail.mouyahada@viacesi.fr",
                            IsBusiness = false,
                            MotDePasse = "TzxBcqT+MIzryEDaZlFx9TSEmx/KEB6vY11o+0Uzk9s=",
                            Nom = "Nos",
                            Prenom = "",
                            Role = 1,
                            SIREN = "515DE1454D56E46",
                            Tel = "+3374075061"
                        },
                        new
                        {
                            Id = 2,
                            DateInscription = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(8302),
                            DateModification = new DateTime(2023, 2, 9, 2, 37, 25, 831, DateTimeKind.Local).AddTicks(8312),
                            Email = "ismail.mouyahada@viacesi.fr",
                            IsBusiness = false,
                            MotDePasse = "TzxBcqT+MIzryEDaZlFx9TSEmx/KEB6vY11o+0Uzk9s=",
                            Nom = "Nos",
                            Prenom = "",
                            Role = 1,
                            SIREN = "DE561D5E156564",
                            Tel = "+3374075061"
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameVille")
                        .HasColumnType("longtext");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("villes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameVille = "Paris",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            NameVille = "Madrid",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 3,
                            NameVille = "Rome",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 4,
                            NameVille = "Paris",
                            RegionId = 4
                        });
                });

            modelBuilder.Entity("NegoSudAPI.Models.Adresse", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Catalogue", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Commande", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("NegoSudAPI.Models.ElemCommande", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Commande", "Commande")
                        .WithMany("ElemCommandes")
                        .HasForeignKey("CommandeId");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("NegoSudAPI.Models.ElemFacture", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Facture", "Facture")
                        .WithMany()
                        .HasForeignKey("FactureId");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Facture", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Inventaire", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Magasin", "Magasin")
                        .WithMany()
                        .HasForeignKey("MagasinId");

                    b.Navigation("Magasin");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Magasin", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Producteur", "Producteur")
                        .WithMany()
                        .HasForeignKey("ProducteurId");

                    b.Navigation("Producteur");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Producteur", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Produit", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Categorie", "Categorie")
                        .WithMany("Produit")
                        .HasForeignKey("CategorieId");

                    b.HasOne("NegoSudAPI.Models.ElemCommande", null)
                        .WithMany("Produits")
                        .HasForeignKey("ElemCommandeId");

                    b.HasOne("NegoSudAPI.Models.ElemFacture", null)
                        .WithMany("Produits")
                        .HasForeignKey("ElemFactureId");

                    b.HasOne("NegoSudAPI.Models.Fournisseur", null)
                        .WithMany("Produits")
                        .HasForeignKey("FournisseurId");

                    b.HasOne("NegoSudAPI.Models.Inventaire", null)
                        .WithMany("Produits")
                        .HasForeignKey("InventaireId");

                    b.HasOne("NegoSudAPI.Models.Producteur", "Producteur")
                        .WithMany()
                        .HasForeignKey("ProducteurId");

                    b.Navigation("Categorie");

                    b.Navigation("Producteur");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Region", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("PaysId");

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Ville", b =>
                {
                    b.HasOne("NegoSudAPI.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Categorie", b =>
                {
                    b.Navigation("Produit");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Commande", b =>
                {
                    b.Navigation("ElemCommandes");
                });

            modelBuilder.Entity("NegoSudAPI.Models.ElemCommande", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("NegoSudAPI.Models.ElemFacture", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Fournisseur", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("NegoSudAPI.Models.Inventaire", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
